apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent-elk
  labels:
    name: zabbix-agent-elk
  namespace: stage
spec:
  selector:
     matchLabels:
       name: zabbix-agent-elk
  replicas: 2
  template:
    metadata:
      labels:
        name: zabbix-agent-elk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "node-type"
                operator: In
                values:
                - stage-entry
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zabbix-agent-elk
        image: 143068653284.dkr.ecr.us-east-1.amazonaws.com/zabbix-agent-elk:latest
        ports:
          - containerPort: 10050
        imagePullPolicy: IfNotPresent
        env:
          - name: ZBX_HOSTNAME
            value: zabbix-agent-elk
          - name: ZBX_SERVER_HOST
            value: 10.244.2.1,10.244.3.1,10.244.4.1,10.244.5.1,10.244.6.1,10.244.2.0,10.244.3.0,10.244.4.0,10.244.5.0,10.244.6.0,10.0.66.32
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent-elk
  labels:
     app: zabbix-agent-elk
  namespace: stage
spec:
  type: NodePort
  ports:
    - port: 10050
      nodePort: 32050
      name: zaport
  selector:
    name: zabbix-agent-elk

